/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all quizzes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of quizzes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Quiz title
                             * @example Math Quiz
                             */
                            title: string;
                            questions: {
                                /**
                                 * @description The question text
                                 * @example What is 2+2?
                                 */
                                questionText: string;
                                /**
                                 * @description Question type
                                 * @example mcq
                                 * @enum {string}
                                 */
                                type: "mcq" | "true_false" | "text";
                                /**
                                 * @description Options for MCQ
                                 * @example [
                                 *       "1",
                                 *       "2",
                                 *       "3",
                                 *       "4"
                                 *     ]
                                 */
                                options?: string[];
                                /**
                                 * @description Correct answer
                                 * @example 4
                                 */
                                correctAnswer: string | boolean;
                            }[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        /** Create quiz */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Quiz title
                         * @example Math Quiz
                         */
                        title: string;
                        questions: {
                            /**
                             * @description The question text
                             * @example What is 2+2?
                             */
                            questionText: string;
                            /**
                             * @description Question type
                             * @example mcq
                             * @enum {string}
                             */
                            type: "mcq" | "true_false" | "text";
                            /**
                             * @description Options for MCQ
                             * @example [
                             *       "1",
                             *       "2",
                             *       "3",
                             *       "4"
                             *     ]
                             */
                            options?: string[];
                            /**
                             * @description Correct answer
                             * @example 4
                             */
                            correctAnswer: string | boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Quiz created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attempts/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit quiz */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Quiz ID
                         * @example 64f123abc
                         */
                        quizId: string;
                        answers: {
                            questionId: string;
                            answer: string | boolean;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
